[package]
name = "plt-types"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
concordium_base.workspace = true

[dev-dependencies]
hex.workspace = true
proptest.workspace = true