[workspace]
resolver = "3"

members = [
    "plt-scheduler",
    "plt-token-module"
]

[workspace.dependencies]
plt-token-module = {path = "plt-token-module"}

concordium_base = {path = "../concordium-base/rust-src/concordium_base"}

assert_matches = "1.5.0"
libc = "0.2.178"
thiserror = "2.0.17"
