version: '3'
services:
  bootstrapper:
    image: concordium/dev-node:latest
    entrypoint: /p2p_bootstrapper-cli
    environment:
    - RUST_BACKTRACE=1
    - RUST_LOG=info
    - CONCORDIUM_NODE_BOOTSTRAPPER_REGENESIS_BLOCK_HASHES_FILE=/genesis-data/genesis-${NUM_BAKERS}-bakers/genesis_hash
  collector_backend:
    image: concordium/dev-node:latest
    entrypoint: /node-collector-backend
    environment:
    - RUST_BACKTRACE=1
    - RUST_LOG=info
    - COLLECTOR_BACKEND_ADDRESS=0.0.0.0
    - COLLECTOR_BACKEND_PORT=10000
    ports:
    - "12000:10000"
  baker_id_gen:
    image: concordium/dev-node:latest
    entrypoint: /baker_id_generator
  baker:
    image: concordium/dev-node:latest
    depends_on:
    - bootstrapper
    - baker_id_gen
    entrypoint: /node-entrypoint.sh
    environment:
    - RUST_BACKTRACE=1
    - RUST_LOG=info
    - GENESIS_DATA_PATH=/genesis-data/genesis-${NUM_BAKERS}-bakers
    - BAKER_ID_GEN_DNS=baker_id_gen
    - CONCORDIUM_NODE_CONNECTION_DESIRED_NODES=${DESIRED_PEERS}
    - CONCORDIUM_NODE_CONNECTION_BOOTSTRAP_NODES=bootstrapper:8888
    - CONCORDIUM_NODE_EXTERNAL_PORT=8888
    - CONCORDIUM_NODE_RPC_SERVER_ADDR=0.0.0.0
    ports:
    - "10000"
  collector:
    image: concordium/dev-node:latest
    entrypoint: /collector-entrypoint.sh
    depends_on:
    - baker
    - collector_backend
    environment:
    - RUST_BACKTRACE=1
    - RUST_LOG=info
    - NUM_BAKERS=${NUM_BAKERS}
    - NODE_DNS_BASE=docker-compose_baker
    - COLLECTOR_SLEEP=${COLLECTOR_SLEEP}
    - CONCORDIUM_NODE_COLLECTOR_URL=http://collector_backend:10000/nodes/post
