version: '3'
services:
    bootstrapper:
        image: concordium/dev-client:latest
        depends_on:
            - baker_id_gen
            - collector_backend
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=info
            - MODE=local_bootstrapper
            - EXTRA_ARGS=${EXTRA_ARGS}
        entrypoint:
            - /start.sh
    collector_backend:
        image: concordium/dev-client:latest
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=info
            - MODE=local_collector_backend
            - COLLECTOR_BACKEND_PORT=10000
            - COLLECTOR_BACKEND_HOST=0.0.0.0
            - EXTRA_ARGS=${EXTRA_ARGS}
        entrypoint:
            - /start.sh
        ports:
            - "12000:10000"
    baker_id_gen:
        image: concordium/dev-client:latest
        entrypoint:
            - /baker_id_generator
    baker:
        image: concordium/dev-client:latest
        depends_on:
            - bootstrapper
        entrypoint:
            - /start.sh
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=info
            - DESIRED_PEERS=${DESIRED_PEERS}
            - BOOTSTRAP_FIRST_NODE=bootstrapper:8888
            - EXTERNAL_PORT=8888
            - NUM_BAKERS=${NUM_BAKERS}
            - MODE=local_basic
            - DATA_DIR=/var/lib/concordium/data
            - RPC_SERVER_ADDR=0.0.0.0
            - EXTRA_ARGS=${EXTRA_ARGS}
        ports:
            - "11100-11500:10000"
    collector:
        image: concordium/dev-client:latest
        depends_on:
            - baker
        environment:
            - RUST_BACKTRACE=1
            - RUST_LOG=info
            - MODE=local_collector
            - NUM_BAKERS=${NUM_BAKERS}
            - COLLECTOR_SLEEP=${COLLECTOR_SLEEP}
            - COLLECTOR_URL=http://collector_backend:10000/nodes/post
            - EXTRA_ARGS=${EXTRA_ARGS}
        entrypoint:
            - /start.sh